# version: '3.8'

services:

  mysqlDB:
    image: mysql:latest
    container_name: mysqlDB
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: joc_de_daus
      MYSQL_USER: joc 
      MYSQL_PASSWORD: 7
    ports:
      - 3308:3306
    networks:
      - joc_net
    volumes:
      - mysqldata:/var/lib/mysql
    # Afegeixo per retardar entrada de la app
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=root_password"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Joc_svc
    ports:
      - 3001:3001
    networks:
      - joc_net
    links:
      - mysqlDB
    depends_on:
      mysqlDB:
        condition: service_healthy  # Comprovant que el servidor estigui actiu i receptiu
    # environment:
    #   - DB_HOST=mysqlDB
    #   - DB_PORT=3306
    #   - DB_USER=joc
    #   - DB_PASSWORD=7
    #   - DB_NAME=joc_de_daus

volumes: 
  mysqldata: {}

networks:
  joc_net:
    driver: bridge