version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: joc-de-daus
      MYSQL_USER: joc 
      MYSQL_PASSWORD: 7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

 
